/** Auto Generated - 2024/11/8 13:26:55 */
export type TWatchSection =
    "editor.colorScheme" |
    "editor.fontSize" |
    "editor.fontFamily" |
    "editor.fontFmyCHS" |
    "editor.lineHeight" |
    "editor.onlyHighlightWord" |
    "editor.insertSpaces" |
    "editor.wordWrap" |
    "editor.wordWrapMode" |
    "editor.caretWidth" |
    "editor.showEndOfLine" |
    "editor.wordSeparators" |
    "editor.tabSize" |
    "editor.multiCursorModifier" |
    "editor.mouseWheelZoom" |
    "editor.guessIndent" |
    "editor.scrollBeyondLastLine" |
    "editor.contentAssistSelectionMode" |
    "editor.hover.assist" |
    "editor.foldedCodeExpandMode" |
    "editor.showLastLineWhenFolded" |
    "editor.saveOnFocusLost" |
    "editor.showDefaultEndOfLine" |
    "editor.formatOnSave" |
    "editor.codeassist" |
    "editor.inlineassist" |
    "editor.inlineassist.toolbar" |
    "editor.codeassistKeyTab" |
    "editor.codeassistFontSize" |
    "editor.triggerChars" |
    "editor.codeassist.timeout" |
    "editor.codeassist.px2rem.enabel" |
    "editor.codeassist.px2rem.proportion" |
    "editor.codeassist.px2rem.decimalLength" |
    "editor.codeassist.px2upx.enabel" |
    "editor.codeassist.px2upx.proportion" |
    "editor.codeassist.px2upx.decimalLength" |
    "editor.matchesChars.enable" |
    "editor.matchesChars" |
    "editor.wordChars" |
    "editor.renderWhitespace" |
    "editor.editorConfigSupport" |
    "editor.viewIndentationGuides" |
    "editor.longLineIndicator" |
    "editor.longLineIndicatorColumn" |
    "editor.minimap.enabled" |
    "editor.minimap.maxPixelWidth" |
    "editor.scrollbarHoverPreview.enabled" |
    "editor.saveFoldStatus.enabled" |
    "markdown.pasteSurroundWithCodeBlock" |
    "explorer.fontSize" |
    "explorer.fileReveal.policy" |
    "explorer.showClosedProject" |
    "explorer.iconTheme" |
    "explorer.expandsOnClick" |
    "explorer.folder.openExplorerViewOnClick" |
    "explorer.confirmDragAndDrop" |
    "logInfo.auto.reportCrash" |
    "software.update.settings" |
    "editor.autoHandoffChinesePunctuation" |
    "files.associations.types.mdfile" |
    "files.associations.suffixs" |
    "files.associations.contextmenu" |
    "files.associations" |
    "files.exclude" |
    "dir.exclude" |
    "localHistory.file.maxBackupCount" |
    "localHistory.file.maxBackupSize" |
    "localHistory.file.maxBackupDays" |
    "adb.path" |
    "android.simulator.port" |
    "node.run.memoryParam" |
    "uniappx.kotlin.compiler.memory" |
    "uts-development-android.gradleHome" |
    "uts-development-android.javaHome" |
    "uts-development-android.sdkDir" |
    "harmony.devTools.path" |
    "terminal.maxcount" |
    "browsers.config" |
    "builtin.web.server.port" |
    "windows.runBrowserAutoRefresh" |
    "webServer.config" |
    "weApp.devTools.path" |
    "view.remoteDebug.openOnRunDevice" |
    "cloud.runinlocal.timeout" |
    "terminal.type" |
    "npm.path" |
    "node.path" |
    "workbench.titleBar.useNativeStyle" |
    "query.timeout" |
    "javascript.triggerChars" |
    "javascript.validate.enable" |
    "typescript.triggerChars" |
    "typescript.validate.enable" |
    "uts.validate.enable" |
    "vue.triggerChars" |
    "vue.validate.enable" |
    "html.triggerChars" |
    "css.triggerChars" |
    "css.validate.enable" |
    "json.triggerChars" |
    "emmet.codeassist"
